name: Build with Makefile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential fltk1.3-dev libglu1-mesa-dev libgl1-mesa-dev xvfb

      - name: Build project using Makefile
        run: make

      - name: Run app (headless test)
        run: |
          set -e
          xvfb-run timeout 5s make run | tee run_output.log
          grep "Bobcat UI Application Running..." run_output.log