name: Steam plug Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y build-essential fltk1.3-dev libglu1-mesa-dev libgl1-mesa-dev xvfb
      - name: Build project using Makefile
        run: make

      - name: Run app test (SteamPlug)
        if: runner.os == 'Linux'
        run: |
          set -e
          xvfb-run timeout 5s make run | tee run_output.log
          grep "Bobcat UI Application Running..." run_output.log