name: Steamplug environment build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-gcc12-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-12 fltk1.3-dev libglu1-mesa-dev libgl1-mesa-dev xvfb
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 100
          gcc --version
          g++ --version

      - name: Build project
        run: make CXX=g++-12

      - name: Run app test
        run: |
          set -e
          xvfb-run timeout 5s make run | tee run_output.log
          grep "Bobcat UI Application Running..." run_output.log